### ISSUE TITLE
Rewrite Dockefile with less RUN command

### ISSUE THREAD

**Issue by Guilhermeslucas** [alexellis/holiday-lights-hack#1]
Hi @alexellis , really nice project. I was wondering if I can contribute to this project by rewriting the Dockerfile, since we can avoid to use so many run commands like this [article](https://docs.docker.com/v17.09/engine/userguide/eng-image/dockerfile_best-practices/) recommends.
Thanks a lot!

**Comment by alexellis** [comment]
Hi I'm glad it was useful for you.

I won't be able to test the PR so won't be able to merge it. Feel free to maintain your own fork. 

Alex
